version: '3.8'

services:
  minnakaiwa:
    build: .
    container_name: minnakaiwa-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./api:/app/api
      - ./api/static/assets:/app/api/static/assets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx for production
  nginx:
    image: nginx:alpine
    container_name: minnakaiwa-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - minnakaiwa
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: minnakaiwa-network 